<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[3]=array(2,1,1,'5Lqn5ZOB5LiA57G7');
$cfg_Cs[4]=array(2,1,1,'5Lqn5ZOB5LqM57G7');
$cfg_Cs[5]=array(2,1,1,'5Lqn5ZOB5LiJ57G7');
$cfg_Cs[6]=array(2,1,1,'5Lqn5ZOB5Zub57G7');
$cfg_Cs[7]=array(0,1,1,'6YeR5q+b5bCP55+l6K+G');
$cfg_Cs[8]=array(0,1,1,'54ix54uX5Lq65aOr');
$cfg_Cs[9]=array(0,1,1,'5Yqg5YWl5oiR5Lus');
$cfg_Cs[10]=array(0,1,1,'5ZKo6K+i5oiR5Lus');
$cfg_Cs[11]=array(0,1,1,'6aaW6aG15bm754Gv');
?>