<div class="pro_item_list pro1 wow bounceInUp" data-wow-delay=".4s"><a href='[field:arcurl/]'>
          <div class="pro_item_left">
            <div class="pro_item_title">[field:title/]</div>
            <div class="pro_item_desc">[field:description function="cn_substr(@me,300)"/]...</div>
          </div>
          <div class="pro_item_right">
            <div class="pro_item_img"><img src='[field:picname/]' /></div>
          </div>
          </a></div>