<div class="pro_item_list pro2 wow bounceInUp" data-wow-delay=".6s"><a href='[field:arcurl/]'>
          <div class="pro_item_left2">
            <div class="pro_item_title">[field:title/]</div>
            <div class="pro_item_desc">[field:description function="cn_substr(@me,300)"/]...</div>
          </div>
          <div class="pro_item_right2">
            <div class="pro_item_img"><img src='[field:picname/]' /></div>
          </div>
          </a></div>