<div class="art_list wow fadeInUp">
              <div class="art_img"><a href='[field:arcurl/]'><img src='[field:picname/]'/></a></div>
              <div class="art_right">
                <div class="art_title"><a href='[field:arcurl/]' >[field:title/]</a></div>
                <div class="art_author"><span>点击：[field:click/]</span><span>作者：[field:writer/]</span> <span>日期：[field:pubdate function="MyDate('Y/m/d',@me)"/]</span></div>
                <div class="art_des">[field:description function="cn_substr(@me,200)"/]...<br/>
                </div>
                <a href='[field:arcurl/]' class='art_more'>查看更多>></a></div>
            </div>