<div class="col-lg-4 col-md-6 col-xs-12 wow fadeInUp" data-wow-delay=".2s">
          <div class="service_item">
            <div class="service_item_img"><img src="[field:picname/]" /></div>
            <div class="service_right">
              <div class="service_item_title"><a href="[field:arcurl/]">[field:title/]</a></div>
              <div class="service_item_desc">[field:description function="cn_substr(@me,160)"/]...<a href="[field:arcurl/]" class="service_more">更多>></a></div>
            </div>
          </div>
        </div>