<?php
$z[0]=Array("pubdate","",125,168);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",205,250);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",356,371);
$z[2][4]=array();
$z[3]=Array("title","",373,387);
$z[3][4]=array();
$z[4]=Array("description","",439,489);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,200)";
$z[5]=Array("arcurl","",501,516);
$z[5][4]=array();

?>