<div class="news_item wow fadeInUp" data-wow-delay=".2s">
          <div class="news_item_time"><span class="news_item_day">[field:pubdate function="MyDate('d',@me)"/]</span><span class="news_item_month">[field:pubdate function="MyDate('Y-m',@me)"/]</span></div>
          <div class="news_item_right">
            <div class="news_item_title"><a href="[field:arcurl/]">[field:title/]</a></div>
            <div class="news_item_desc">[field:description function="cn_substr(@me,200)"/]...<a href="[field:arcurl/]" class="news_more">More>></a></div>
          </div>
        </div>