<?php
$z[0]=Array("channel","\r\n          <li>><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n          ",186,411);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[1]=Array("global","",493,515);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",538,559);
$z[2][4]=array();
$z[2][4]['name']="cfg_yx";
$z[3]=Array("global","",582,604);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",645,671);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",672,696);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1268,1290);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";
$z[7]=Array("global","",1379,1401);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";
$z[8]=Array("type"," <a href=\"[field:typelink/]\"><span class=\"icon-user\"></span>联系</a>",1482,1587);
$z[8][4]=array();
$z[8][4]['typeid']="10";

?>