<?php
$z[0]=Array("global","",97,118);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("global","",213,234);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("type"," <a href=\"[field:typelink/]\">[field:typename/]</a>",598,683);
$z[2][4]=array();
$z[2][4]['typeid']="10";
$z[3]=Array("global","",853,879);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",933,959);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",1114,1206);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",1243,1464);
$z[6][4]=array();
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[7]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",1713,1936);
$z[7][4]=array();
$z[7][4]['type']="top";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";

?>