<?php
$z[0]=Array("channel","\r\n          <li class='first_cat'><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",196,448);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['typeid']="2";
$z[0][4]['currentstyle']="<li class='first_cat'><a href='~typelink~'>~typename~</a></li>";
$z[1]=Array("global","",702,728);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",814,836);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",904,925);
$z[3][4]=array();
$z[3][4]['name']="cfg_yx";
$z[4]=Array("global","",970,992);
$z[4][4]=array();
$z[4][4]['name']="cfg_add";

?>